version: '3'

services:
  gemini:
    build: ./
    container_name: gemini
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - /srv/docker/gemini/capsule:/usr/local/gemini/geminidocs
    ports:
      - 1965:1965
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=false

